name: Deploy to GKE via Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ vars.GCP_PROJECT }}
          install_components: "gke-gcloud-auth-plugin"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="project_id=${{ vars.GCP_PROJECT }}" \
            -var="region=${{ vars.GKE_REGION }}" \
            -var="zone=${{ vars.GCP_ZONE }}" \
            -var="cluster_name=${{ vars.GKE_CLUSTER_NAME }}"
        working-directory: ./terraform
